Create Trade settlement form and show data page
it-kmitl-2018/group5 pull request #28
Opened 2018-03-06 04:42 UTC by mildminihi

Add TradeSettlement.java : is Controller to mapping model from html
Add createtradesettlement.html : is html include form
Add showtradesettlement.html : is html to show data

2018-03-07 04:08 UTC, champillon requested changes
ฝากชี้แจง และเพิ่ม test ด้วยครับ

2018-03-07 04:08 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    public String create(Model model) {
Model ที่รับนี่คืออะไรครับ?

2018-03-07 04:08 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +        model.addAttribute("tradeSettlementMonetarySummation",new TradeSettlementMonetarySummation());
ทำไมรับข้อมูลมาแล้วต้อง addAtrribute ด้วยครับ?

2018-03-07 04:08 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    @GetMapping("/create/settlement")
จริงๆ สร้างควรเป็น Post รึป่วครับ?

2018-03-07 04:08 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    @PostMapping("/create/settlement")
ทำไมดึงข้อมูลไม่เป็น Get หล่ะครับ?

2018-03-08 07:06 UTC, mildminihi commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    public String create(Model model) {
คือ model ของ trade settlement ครับ

2018-03-08 07:37 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    public String create(Model model) {
พี่ว่า model ที่รับจากหน้าจอ น่าจะเป็น ใบกำกับภาษี ประกอบด้วย ผู้ซื้อ, ผู้ขาย, รายการที่ซื้อ และราคมรวม มากกว่านะ ตั้งชื่อประมาณนี้ จะ maintain code ง่ายกว่า

2018-03-08 07:41 UTC, mildminihi commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    public String create(Model model) {
โอเคครับพี่

2018-03-19 13:00 UTC, mildminihi commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    @PostMapping("/create/settlement")
อันนี้เป็น post ส่งข้อมูลไปอีกหน้าอ่ะครับ

2018-03-19 13:07 UTC, mildminihi commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    @GetMapping("/create/settlement")
จากที่ผมอ่านในเว็บมามันน่าจะใช้ get เพื่อดึงค่าจาก form ที่ submit มาอ่ะครับ ผมทำตามเว็บนี้อ่ะครับ https://spring.io/guides/gs/handling-form-submission/

2018-03-19 13:08 UTC, mildminihi commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +        model.addAttribute("tradeSettlementMonetarySummation",new TradeSettlementMonetarySummation());
เพื่อยัดเข้าไปใน model ไว้ใช้ในการส่งค่าอ่ะครับ

2018-03-19 13:23 UTC, mildminihi commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    public String create(Model model) {
เพิ่มtestแล้วครับ

2018-03-19 14:00 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    @GetMapping("/create/settlement")
อ่ออออออออ ไว้พรุ่งนี้สอน RESTful url ให้ ตั้งแบบนี้มันแปลกๆ

2018-03-19 14:01 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    @PostMapping("/create/settlement")
เช

2018-03-19 14:03 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +        model.addAttribute("tradeSettlementMonetarySummation",new TradeSettlementMonetarySummation());
PR นี้เอาแบบนี้ก่อนก็ได้ แต่เราว่าส่วนข้อมูลที่ชื่อ class มันยากๆ ต้องตรงกับ XML ของ ETDA นี่ ย้ายไปอยู่ในส่วน converter ดีกว่ามั้ย ไม่ควรมาทำตั้งแต่ controller อ่ะ controller มันควรคุมว่า request ที่เข้ามา ถ้าไม่มี error ก็ return result แต่ถ้ามี error ก็ map error message นั้นๆ คืนให้หน้าบ้าน

2018-03-19 14:03 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/controllers/TradeSettlement.java
> +    @PostMapping("/create/settlement")
เช

2018-03-21 16:08 UTC, closed without merging