Add enum reason description
it-kmitl-2018/group5 pull request #33
Opened 2018-03-06 05:41 UTC by nanntch

- add enum ReasonDescription
- add enum ReasonDescription test

2018-03-06 10:31 UTC, champillon requested changes
ฝากแก้ไขด้วยครับ

2018-03-06 10:31 UTC, champillon commented on src/test/java/th/ac/kmitl/it/soa/group5/etaxinvoice/models/ReasonDescriptionModelTest.java
> +    public static void main(String[] args) {
ทำไมใช้ชื่อ main เป็น test case หล่ะ?

2018-03-06 10:31 UTC, champillon commented on src/test/java/th/ac/kmitl/it/soa/group5/etaxinvoice/models/ReasonDescriptionModelTest.java
> +        import org.junit.Test;
ทำไมเบี้ยวหล่ะ

2018-03-06 10:31 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/models/ReasonDescriptionModel.java
> +public class ReasonDescriptionModel {
ทำไมใช้ชื่อนี้หล่ะ ไม่สื่อเลย

2018-03-07 04:39 UTC, champillon reviewed
ฝากชี้แจงด้วยครับ

2018-03-07 04:39 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/models/ReasonForDiscountOrCharge.java
> +public class ReasonForDiscountOrCharge {
ทำไมต้องทำ inner class ด้วยครับ

2018-03-20 01:35 UTC, champillon approved these changes
LGTM la

2018-03-20 01:35 UTC, champillon commented
กำ กด approve ไปแล้ว ลืมทักไปว่า enum ควรอยู่ใน pacakge model หรอ?

2018-03-20 01:36 UTC, mahasak approved these changes
LGTM

2018-03-20 01:42 UTC, merged

2018-03-20 01:44 UTC, champillon commented
คะแนนครับ 3.25 คะแนน
5.1 การ design เป็น components เพื่อทำให้คนอื่นทำงานร่วมกันต่อได้ง่าย => 0.75 คะแนน
5.2 คุณภาพของการตั้งชื่อตัวแปร, ฟังก์ชั่น และความเรียบร้อยของ code => 1 คะแนน
5.3 ความยากเชิงเทคนิคที่นำมาประยุกต์ใช้ เช่น แปลง XML Schema เป็น Java code => 0 คะแนน
5.4 รายละเอียดการตั้งชื่อใน PR name และ commit log รวมทั้งรายละเอียดที่บรรยายใน issue ของ PR นั้นๆ => 0.5 คะแนน
5.5 ความสอดคล้องกันกับ PR อื่นๆของทีม ที่ทำงานร่วมกันได้ดี => 1 คะแนน