Add TaxPayerIdTypeCode and Test
it-kmitl-2018/group5 pull request #60
Opened 2018-05-13 07:09 UTC by mildminihi

เพิ่ม TaxPayerIDTypeCode ตามเอกสารหน้าที่ 52

Add file
- TaxPayerIdTypeCode.java
- TaxPayerIdTypeCodeTest.java

2018-05-13 11:34 UTC, champillon approved these changes

2018-05-13 15:27 UTC, keattiwut requested changes
ไปเพิ่ม parse ด้วยครับ

2018-05-13 18:20 UTC, mildminihi commented
@keattiwut แบบนี้ป่ะครับพี่ผมยังไม่ค่อยแน่ใจว่าถูกไหมอ่ะครับ

2018-05-13 18:21 UTC, mildminihi commented
ถ้าถูกเดี๋ยวผมไปแก้อีกอันครับ

2018-05-13 23:24 UTC, keattiwut reviewed
ยังไม่เห็นแก้นะ

2018-05-14 02:27 UTC, mildminihi commented
@keattiwut ขอโทษครับพี่ผมไม่ทราบจริงๆ Parse สำหรับ enum มันคืออะไรครับพี่แนะนำหน่อย ขอบคุณครับ

2018-05-14 02:46 UTC, keattiwut reviewed
น้องมี enum class ใช่ไหม ทีนี้ ลองนึกว่า เวลา เรามี TaxPayerType code เช่น TAXID แล้วน้องต้องการให้มันเป็น enum แต่เราก็ใช้ valueOf ไม่ได้เพราะ มันใช้ name ของ Enum
คำถามคือควรทำอย่างไร? คำใบ้ เปิด google พิมพ์ "java parse string to enum" น่าจะเจอ ขอให้โชคดี

2018-05-14 03:27 UTC, mildminihi commented
@keattiwut ถูกป่ะพี่

2018-05-14 04:18 UTC, keattiwut requested changes
เพิ่ม code แล้วควร เพิ่ม test ด้วยครับ

2018-05-14 04:18 UTC, keattiwut commented on src/main/java/th/ac/kmitl/it/soa/group5/etaxinvoice/definitions/TaxPayerIdTypeCode.java
> +        return mapper.get(taxPlayerIdCode);
แล้วถ้า code ที่ส่งมาไม่มีอยู่ใน enum ควรต้อง throw อะไรออกไปบ้างไหม?

2018-05-14 06:00 UTC, keattiwut approved these changes

2018-05-14 06:02 UTC, mildminihi commented
@keattiwut ขอบคุณครับพี่เดี๋ยวผมไปแก้อีก pr นึงครับ

2018-05-14 07:13 UTC, merged

2018-05-20 17:07 UTC, champillon commented
2.25 คะแนน