Add ReferenceTypeCode and Test
it-kmitl-2018/group5 pull request #62
Opened 2018-05-13 08:05 UTC by mildminihi

เพิ่มตามเอกสารหน้า 49-50

Add file
- ReferenceTypeCode.java
- ReferenceTypeCodeTest.java

2018-05-13 11:37 UTC, champillon approved these changes

2018-05-13 15:26 UTC, keattiwut requested changes
Code โอเคแล้ว แต่อยากให้เพิ่ม Parse สำหรับ enum ด้วยนะ

2018-05-13 17:42 UTC, mildminihi commented
@keattiwut Parse นี่ใช่ .valueOf() ป่ะครับ

2018-05-14 06:21 UTC, keattiwut approved these changes

2018-05-14 07:15 UTC, merged

2018-05-20 17:06 UTC, champillon commented
2.25 คะแนน